#粉丝通知
query FansNotificationsQuery($filter: [NotificationEnum], $limit: Int, $offset: Int) {
    notifications(filter: $filter, limit: $limit, offset: $offset, read_filter: 0) {
        type
        created_at
        follow {
            id
            created_at
            user {
                id
                name
                avatar
                gender
                followed_user_status
                level {
                    id
                    level
                }
                profile {
                    age
                }
            }
        }
    }
}