query UserAccountSecurityQuery($id: Int!) {
    user(id: $id) {
        id
        gold
        is_bind_wechat
        ticket
        level {
            id
            name
            ticket_max
            level
            exp
        }
        withdrawInfo {
            amount
            description
        }
        wallet {
            id
            real_name
            pay_account
            pay_info_change_count
            total_withdraw_amount
            available_balance
            balance
            bind_platforms {
                alipay
            }
        }
        profile {
            total_contributes
        }
        today_contributes
        week_contributes
        today_new_questions_count
        today_left_questions_count
        today_withdraw_left
        exchange_rate
        invitations_success_count
        force_alert
        is_bind_dongdezhuan
        dongdezhuanUser {
            id
            name
            account
        }
        DZUser {
            id
            name
            account
        }
        auto_uuid_user
        auto_phone_user
    }
}
