# 答题记录
query answerHistoriesQuery($offset: Int, $limit: Int) {
    user {
        id
        answerHistories(offset: $offset, limit: $limit) {
            id
            correct_count
            question {
                id
                description
            }
        }
    }
}