#智慧点变动记录
query GoldsQuery($user_id: Int, $offset: Int, $limit: Int) {
    golds(user_id: $user_id, offset: $offset, limit: $limit) {
        gold
        balance
        remark
        created_at
    }
}