#重置密码
mutation ResetPasswordMutation($account: String!, $password: String!, $code: String!) {
    resetPassword(account: $account, password: $password, code: $code) {
        id
        account
    }
}