#为8/7-8/23注册的用户重新设置密码
mutation tokenSetPassword($password: String, $token: String) {
    tokenSetPassword(password: $password, token: $token) {
        id
        account
        token
        avatar
        name
        withdrawInfo {
            amount
            description
        }
        wallet {
            id
            real_name
            pay_account
            pay_info_change_count
            total_withdraw_amount
            available_balance
            balance
        }
        profile {
            introduction
            birthday
            age
            total_contributes
        }
        gender
        is_admin
    }
}