#其他用户资料
query UserInfoQuery(
    $id: Int
    $limit: Int
    $offset: Int
    $order: QuestionOrderEnum
    $filter: QuestionFilterEnum
    $QuestionFormEnumType: QuestionFormEnumType
) {
    user(id: $id) {
        id
        name
        avatar
        gender
        follow_users_count
        followers_count
        followed_user_status
        is_admin
        profile {
            sub_name
            birthday
            age
            introduction
        }
        level {
            id
            level
        }
        questions(limit: $limit, offset: $offset, order: $order, filter: $filter, form: $QuestionFormEnumType) {
            id
            gold
            description
            count_likes
            count_comments
            liked
            form
            is_resolved
            created_at
            count
            video {
                id
                width
                height
                url
                cover
                is_ad_video
            }
            user {
                id
                name
                avatar
                followed_user_status
                profile {
                    age
                }
                level {
                    id
                    level
                }
            }
            image {
                id
                width
                height
                path
            }
            category {
                id
                name
            }
        }
    }
}