#提现日志
query WithdrawsQuery($first: Int, $page: Int) {
    withdraws(first: $first, page: $page) {
    	paginatorInfo {
          	currentPage
          	hasMorePages
        }
    	data {
          	id
            status
            amount
            created_at
            remark
            to_platform
        }
    }
}